apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  annotations:
    eventstreams.ibm.com/apicurio-registry-version: '>=2.4'
  name: event-streams
  labels:
    backup.eventstreams.ibm.com/component: eventstreams
  namespace: cp4i
spec:
  version: latest
  license:
    accept: true
    license: L-VTPK-22YZPK
    use: CloudPakForIntegrationNonProduction
  adminApi: {}
  adminUI:
    authentication:
      - type: integrationKeycloak
  apicurioRegistry: {}
  collector: {}
  restProducer: {}
  strimziOverrides:
    kafka:
      replicas: 3
      authorization:
        type: simple
      config:
        inter.broker.protocol.version: '3.5'
        log.cleaner.threads: 6
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 3
        offsets.topic.replication.factor: 3
        default.replication.factor: 3
        min.insync.replicas: 2
      listeners:
        - name: external
          port: 9094
          type: route
          tls: true
          authentication:
            type: scram-sha-512
        - name: tls
          port: 9093
          type: internal
          tls: true
          authentication:
            type: tls
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: development-metrics-config
      storage:
        type: persistent-claim
        class: ocs-storagecluster-ceph-rbd
    zookeeper:
      replicas: 3
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: development-metrics-config
      storage:
        type: persistent-claim
        class: ocs-storagecluster-ceph-rbd
