apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  annotations:
    com.ibm.mq/write-defaults-spec: 'false'
  name: singleinstance-qm
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-VTPK-22YZPK
    use: NonProduction
  queueManager:
    name: QM01
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    storage:
      queueManager:
        type: persistent-claim
        size: 100Mi
      persistedData:
        enabled: true
        size: 100Mi
  version: 9.3.4.1-r1
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true
